version: '3.8'
services:
    backend-flask:
        environment:
            FRONTEND_URL: 'http://localhost:3000/'
            BACKEND_URL: 'http://localhost:4567/'
        build: ./backend-flask
        ports:
            - '4567:4567'
        volumes:
            - ./backend-flask:/backend-flask
    frontend-react-js:
        environment:
            REACT_APP_BACKEND_URL: 'http://localhost:4567/'
        build: ./frontend-react-js
        command: 'docker run -d -p 3000:3000 -v /frontend-react-js/node_modules -v $(pwd):/frontend-react-js --name frontend-app frontend-react-js'
        volumes:
            - ./frontend-react-js:/frontend-react-js
