version: '3.8'
name: cruddar
services:
    backend-flask:
        environment:
            FRONTEND_URL: 'http://172.27.42.5:4000/'
            BACKEND_URL: 'http://172.27.42.5:5000/'
        build:
            context: ./backend-flask
            dockerfile: Dockerfile.dev
        ports:
            - '5000:4567'
        volumes:
            - ./backend-flask:/backend-flask
    frontend-vite:
        restart: unless-stopped
        env_file:
            - ./frontend-vite/.env
        # environment:
        #     REACT_APP_BACKEND_URL: 'http://172.27.42.5:5000/'
        build:
            context: ./frontend-vite
            dockerfile: Dockerfile.dev
        ports:
            - '4000:3000'
        volumes:
            - ./frontend-vite:/app
            - '/app/node_modules'
